name: Destroy review environment

on:
  pull_request:
    types: [closed]

jobs:
  destroy_review_env:
    name: Destroy review environment
    if: github.head_ref != 'main' && github.head_ref != 'dev'
    runs-on: ubuntu-latest
    env:
      ENV_ID: ${{ github.head_ref }}
    steps:
      - name: Checkouts repository
        uses: actions/checkout@v2

      - name: Setups node and npm
        uses: actions/setup-node@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: echo "installing dependencies... (replace with npm install)"

      - name: Destroys review environment
        run: |
          echo "sending destroy signal to $ENV_ID... (replace with real commands)"
      
